# Generated by Django 3.2.9 on 2021-11-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='approved_account',
            new_name='friend_account',
        ),
        migrations.AddField(
            model_name='friend',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friend',
            name='chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
