# Generated by Django 3.2.9 on 2021-11-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_auto_20211127_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='chat',
        ),
    ]
