# Generated by Django 3.2.9 on 2021-11-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_auto_20211112_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Declined',
        ),
    ]
