# Generated by Django 3.2.9 on 2021-11-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_delete_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
