# Generated by Django 3.2.9 on 2021-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_auto_20211128_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friend',
            name='chat',
            field=models.BooleanField(default=False),
        ),
    ]
