# Generated by Django 3.2.9 on 2021-12-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='timestamp',
        ),
    ]
