# Generated by Django 3.2.9 on 2021-11-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='forwaded_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded', to='chat_api.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=700),
        ),
    ]
