# Generated by Django 3.2.9 on 2021-11-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_auto_20211122_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='forwaded_message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded', to='chat_api.message'),
        ),
    ]
