# Generated by Django 3.2.9 on 2021-11-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0003_alter_message_forwaded_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='forwaded_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded', to='chat_api.message'),
        ),
    ]
