# Generated by Django 3.2.9 on 2021-11-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0004_alter_message_forwaded_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
