# Generated by Django 3.2.9 on 2021-11-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0004_auto_20211128_2351'),
        ('chat_api', '0004_auto_20211128_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='profile_api.friend'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='profile_api.friend'),
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
