# Generated by Django 3.2.9 on 2021-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_seen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_seen_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
